{"timestamp": "2025-07-29T00:39:08.757556", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 37, "thread": "MainThread"}
{"timestamp": "2025-07-29T00:39:08.783192", "level": "WARNING", "message": "No se pudo configurar HiDPI: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "create_application", "line": 25, "thread": "MainThread"}
{"timestamp": "2025-07-29T00:39:09.462249", "level": "INFO", "message": "Interfaz de login mostrada", "module": "main", "function": "main", "line": 68, "thread": "MainThread"}
{"timestamp": "2025-07-29T00:39:23.560645", "level": "INFO", "message": "Intento de login para usuario: carlos", "module": "auth_controller", "function": "authenticate", "line": 11, "thread": "MainThread"}
{"timestamp": "2025-07-29T00:39:23.646671", "level": "ERROR", "message": "Error al validar credenciales: no existe la columna «password»\nLINE 1: ...ELECT id FROM users WHERE username = 'carlos' AND password =...\n                                                             ^\n", "module": "auth_service", "function": "validate_credentials", "line": 23, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\services\\auth_service.py\", line 17, in validate_credentials\n    cursor.execute(\npsycopg2.errors.UndefinedColumn: no existe la columna «password»\nLINE 1: ...ELECT id FROM users WHERE username = 'carlos' AND password =...\n                                                             ^\n"}
{"timestamp": "2025-07-29T00:39:23.648166", "level": "WARNING", "message": "Intento de login fallido", "module": "main", "function": "on_login_failed", "line": 57, "thread": "MainThread"}
{"timestamp": "2025-07-29T00:39:32.180345", "level": "INFO", "message": "Intento de login para usuario: carlos", "module": "auth_controller", "function": "authenticate", "line": 11, "thread": "MainThread"}
{"timestamp": "2025-07-29T00:39:32.182074", "level": "ERROR", "message": "Error al validar credenciales: transacción abortada, las órdenes serán ignoradas hasta el fin de bloque de transacción\n", "module": "auth_service", "function": "validate_credentials", "line": 23, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\services\\auth_service.py\", line 17, in validate_credentials\n    cursor.execute(\npsycopg2.errors.InFailedSqlTransaction: transacción abortada, las órdenes serán ignoradas hasta el fin de bloque de transacción\n"}
{"timestamp": "2025-07-29T00:39:32.183070", "level": "WARNING", "message": "Intento de login fallido", "module": "main", "function": "on_login_failed", "line": 57, "thread": "MainThread"}
{"timestamp": "2025-07-29T00:39:45.871713", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 11, "thread": "MainThread"}
{"timestamp": "2025-07-29T00:39:45.873534", "level": "ERROR", "message": "Error al validar credenciales: transacción abortada, las órdenes serán ignoradas hasta el fin de bloque de transacción\n", "module": "auth_service", "function": "validate_credentials", "line": 23, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\services\\auth_service.py\", line 17, in validate_credentials\n    cursor.execute(\npsycopg2.errors.InFailedSqlTransaction: transacción abortada, las órdenes serán ignoradas hasta el fin de bloque de transacción\n"}
{"timestamp": "2025-07-29T00:39:45.875129", "level": "WARNING", "message": "Intento de login fallido", "module": "main", "function": "on_login_failed", "line": 57, "thread": "MainThread"}
{"timestamp": "2025-07-29T00:40:21.540493", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 11, "thread": "MainThread"}
{"timestamp": "2025-07-29T00:40:21.542432", "level": "ERROR", "message": "Error al validar credenciales: transacción abortada, las órdenes serán ignoradas hasta el fin de bloque de transacción\n", "module": "auth_service", "function": "validate_credentials", "line": 23, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\services\\auth_service.py\", line 17, in validate_credentials\n    cursor.execute(\npsycopg2.errors.InFailedSqlTransaction: transacción abortada, las órdenes serán ignoradas hasta el fin de bloque de transacción\n"}
{"timestamp": "2025-07-29T00:40:21.543580", "level": "WARNING", "message": "Intento de login fallido", "module": "main", "function": "on_login_failed", "line": 57, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:02:36.151783", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 37, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:02:36.185480", "level": "WARNING", "message": "No se pudo configurar HiDPI: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "create_application", "line": 25, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:02:36.990044", "level": "INFO", "message": "Interfaz de login mostrada", "module": "main", "function": "main", "line": 68, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:02:44.240471", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 11, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:02:44.263983", "level": "ERROR", "message": "Error al validar credenciales: no existe la columna «password»\nLINE 1: SELECT id FROM users WHERE username = 'luis' AND password = ...\n                                                         ^\n", "module": "auth_service", "function": "validate_credentials", "line": 23, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\services\\auth_service.py\", line 17, in validate_credentials\n    cursor.execute(\npsycopg2.errors.UndefinedColumn: no existe la columna «password»\nLINE 1: SELECT id FROM users WHERE username = 'luis' AND password = ...\n                                                         ^\n"}
{"timestamp": "2025-07-29T11:02:44.263983", "level": "WARNING", "message": "Intento de login fallido", "module": "main", "function": "on_login_failed", "line": 57, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:03:00.006776", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 11, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:03:00.008163", "level": "ERROR", "message": "Error al validar credenciales: transacción abortada, las órdenes serán ignoradas hasta el fin de bloque de transacción\n", "module": "auth_service", "function": "validate_credentials", "line": 23, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\services\\auth_service.py\", line 17, in validate_credentials\n    cursor.execute(\npsycopg2.errors.InFailedSqlTransaction: transacción abortada, las órdenes serán ignoradas hasta el fin de bloque de transacción\n"}
{"timestamp": "2025-07-29T11:03:00.010158", "level": "WARNING", "message": "Intento de login fallido", "module": "main", "function": "on_login_failed", "line": 57, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:03:07.224813", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 11, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:03:07.224813", "level": "ERROR", "message": "Error al validar credenciales: transacción abortada, las órdenes serán ignoradas hasta el fin de bloque de transacción\n", "module": "auth_service", "function": "validate_credentials", "line": 23, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\services\\auth_service.py\", line 17, in validate_credentials\n    cursor.execute(\npsycopg2.errors.InFailedSqlTransaction: transacción abortada, las órdenes serán ignoradas hasta el fin de bloque de transacción\n"}
{"timestamp": "2025-07-29T11:03:07.224813", "level": "WARNING", "message": "Intento de login fallido", "module": "main", "function": "on_login_failed", "line": 57, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:03:33.924917", "level": "CRITICAL", "message": "Excepción no capturada", "module": "main", "function": "handle_exception", "line": 15, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\login_window.py\", line 50, in authenticate\n    QMessageBox.warning(self, \"Error\", \"Credenciales incorrectas\")\n  File \"E:\\MODELO MACHINE LEARNING TOTAL\\EXE\\envs\\nova-desktop\\Lib\\enum.py\", line 720, in __call__\n    def __call__(cls, value, names=_not_given, *values, module=None, qualname=None, type=None, start=1, boundary=None):\n    \nKeyboardInterrupt"}
{"timestamp": "2025-07-29T11:12:42.194886", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 37, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:12:42.216342", "level": "WARNING", "message": "No se pudo configurar HiDPI: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "create_application", "line": 25, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:12:42.279613", "level": "CRITICAL", "message": "Error al iniciar aplicación: LoginWindow.__init__() missing 1 required positional argument: 'auth_controller'", "module": "main", "function": "main", "line": 73, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 45, in main\n    login_window = LoginWindow()\n                   ^^^^^^^^^^^^^\nTypeError: LoginWindow.__init__() missing 1 required positional argument: 'auth_controller'"}
{"timestamp": "2025-07-29T11:12:53.143848", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 37, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:12:53.170609", "level": "WARNING", "message": "No se pudo configurar HiDPI: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "create_application", "line": 25, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:12:53.219411", "level": "CRITICAL", "message": "Error al iniciar aplicación: LoginWindow.__init__() missing 1 required positional argument: 'auth_controller'", "module": "main", "function": "main", "line": 73, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 45, in main\n    login_window = LoginWindow()\n                   ^^^^^^^^^^^^^\nTypeError: LoginWindow.__init__() missing 1 required positional argument: 'auth_controller'"}
{"timestamp": "2025-07-29T11:15:10.732488", "level": "CRITICAL", "message": "Excepción no capturada", "module": "logger", "function": "handle_exception", "line": 138, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 12, in <module>\n    from app.utils.logger import setup_logging\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\__init__.py\", line 17, in <module>\n    from .main import main  # noqa\n    ^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 14, in <module>\n    from app.controllers.auth_controller import AuthController\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\controllers\\auth_controller.py\", line 2, in <module>\n    from app.services.auth_service import AuthService\nImportError: cannot import name 'AuthService' from 'app.services.auth_service' (E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\services\\auth_service.py)"}
{"timestamp": "2025-07-29T11:15:14.905193", "level": "CRITICAL", "message": "Excepción no capturada", "module": "logger", "function": "handle_exception", "line": 138, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 12, in <module>\n    from app.utils.logger import setup_logging\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\__init__.py\", line 17, in <module>\n    from .main import main  # noqa\n    ^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 14, in <module>\n    from app.controllers.auth_controller import AuthController\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\controllers\\auth_controller.py\", line 2, in <module>\n    from app.services.auth_service import AuthService\nImportError: cannot import name 'AuthService' from 'app.services.auth_service' (E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\services\\auth_service.py)"}
{"timestamp": "2025-07-29T11:23:19.800171", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 44, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:23:19.822643", "level": "WARNING", "message": "No se pudo configurar HiDPI: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "create_application", "line": 32, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:23:19.956999", "level": "CRITICAL", "message": "Error al iniciar aplicación: 'utf-8' codec can't decode byte 0xf3 in position 85: invalid continuation byte", "module": "main", "function": "main", "line": 69, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 49, in main\n    db = Database()\n         ^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\utils\\database.py\", line 13, in __init__\n    self.connection_pool = self._create_connection_pool()\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\utils\\database.py\", line 17, in _create_connection_pool\n    return psycopg2.pool.SimpleConnectionPool(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\MODELO MACHINE LEARNING TOTAL\\EXE\\envs\\nova-desktop\\Lib\\site-packages\\psycopg2\\pool.py\", line 59, in __init__\n    self._connect()\n  File \"E:\\MODELO MACHINE LEARNING TOTAL\\EXE\\envs\\nova-desktop\\Lib\\site-packages\\psycopg2\\pool.py\", line 63, in _connect\n    conn = psycopg2.connect(*self._args, **self._kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\MODELO MACHINE LEARNING TOTAL\\EXE\\envs\\nova-desktop\\Lib\\site-packages\\psycopg2\\__init__.py\", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 85: invalid continuation byte"}
{"timestamp": "2025-07-29T11:23:23.127699", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 44, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:23:23.156578", "level": "WARNING", "message": "No se pudo configurar HiDPI: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "create_application", "line": 32, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:23:23.278974", "level": "CRITICAL", "message": "Error al iniciar aplicación: 'utf-8' codec can't decode byte 0xf3 in position 85: invalid continuation byte", "module": "main", "function": "main", "line": 69, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 49, in main\n    db = Database()\n         ^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\utils\\database.py\", line 13, in __init__\n    self.connection_pool = self._create_connection_pool()\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\utils\\database.py\", line 17, in _create_connection_pool\n    return psycopg2.pool.SimpleConnectionPool(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\MODELO MACHINE LEARNING TOTAL\\EXE\\envs\\nova-desktop\\Lib\\site-packages\\psycopg2\\pool.py\", line 59, in __init__\n    self._connect()\n  File \"E:\\MODELO MACHINE LEARNING TOTAL\\EXE\\envs\\nova-desktop\\Lib\\site-packages\\psycopg2\\pool.py\", line 63, in _connect\n    conn = psycopg2.connect(*self._args, **self._kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\MODELO MACHINE LEARNING TOTAL\\EXE\\envs\\nova-desktop\\Lib\\site-packages\\psycopg2\\__init__.py\", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 85: invalid continuation byte"}
{"timestamp": "2025-07-29T11:27:11.037085", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 44, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:27:11.063768", "level": "WARNING", "message": "No se pudo configurar HiDPI: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "create_application", "line": 32, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:27:11.190528", "level": "CRITICAL", "message": "Error al iniciar aplicación: 'utf-8' codec can't decode byte 0xf3 in position 85: invalid continuation byte", "module": "main", "function": "main", "line": 69, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 49, in main\n    db = Database()\n         ^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\utils\\database.py\", line 13, in __init__\n    self.connection_pool = self._create_connection_pool()\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\utils\\database.py\", line 17, in _create_connection_pool\n    return psycopg2.pool.SimpleConnectionPool(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\MODELO MACHINE LEARNING TOTAL\\EXE\\envs\\nova-desktop\\Lib\\site-packages\\psycopg2\\pool.py\", line 59, in __init__\n    self._connect()\n  File \"E:\\MODELO MACHINE LEARNING TOTAL\\EXE\\envs\\nova-desktop\\Lib\\site-packages\\psycopg2\\pool.py\", line 63, in _connect\n    conn = psycopg2.connect(*self._args, **self._kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\MODELO MACHINE LEARNING TOTAL\\EXE\\envs\\nova-desktop\\Lib\\site-packages\\psycopg2\\__init__.py\", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 85: invalid continuation byte"}
{"timestamp": "2025-07-29T11:29:08.071376", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 44, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:29:08.092287", "level": "WARNING", "message": "No se pudo configurar HiDPI: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "create_application", "line": 32, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:29:08.306109", "level": "INFO", "message": "Interfaz de login mostrada", "module": "main", "function": "main", "line": 64, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:29:13.451677", "level": "ERROR", "message": "Error en autenticación: 'Database' object has no attribute 'ensure_connection'", "module": "login_window", "function": "authenticate", "line": 79, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\login_window.py\", line 66, in authenticate\n    if not self.auth_controller.db.ensure_connection():\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'Database' object has no attribute 'ensure_connection'. Did you mean: 'release_connection'?"}
{"timestamp": "2025-07-29T11:29:31.753137", "level": "ERROR", "message": "Error en autenticación: 'Database' object has no attribute 'ensure_connection'", "module": "login_window", "function": "authenticate", "line": 79, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\login_window.py\", line 66, in authenticate\n    if not self.auth_controller.db.ensure_connection():\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'Database' object has no attribute 'ensure_connection'. Did you mean: 'release_connection'?"}
{"timestamp": "2025-07-29T11:29:34.424285", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 89, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:33:04.249138", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 44, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:33:04.275979", "level": "WARNING", "message": "No se pudo configurar HiDPI: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "create_application", "line": 32, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:33:04.458451", "level": "INFO", "message": "Interfaz de login mostrada", "module": "main", "function": "main", "line": 64, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:33:09.875968", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 13, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:33:09.883003", "level": "ERROR", "message": "Error en autenticación: 'Database' object has no attribute 'connection'", "module": "auth_controller", "function": "authenticate", "line": 16, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\controllers\\auth_controller.py\", line 14, in authenticate\n    return self.auth_service.validate_credentials(username, password)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\services\\auth_service.py\", line 11, in validate_credentials\n    if not self.db.connection:\n           ^^^^^^^^^^^^^^^^^^\nAttributeError: 'Database' object has no attribute 'connection'. Did you mean: 'get_connection'?"}
{"timestamp": "2025-07-29T11:33:09.886943", "level": "WARNING", "message": "Intento fallido para usuario: luis", "module": "login_window", "function": "authenticate", "line": 75, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:33:19.724308", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 13, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:33:19.727369", "level": "ERROR", "message": "Error en autenticación: 'Database' object has no attribute 'connection'", "module": "auth_controller", "function": "authenticate", "line": 16, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\controllers\\auth_controller.py\", line 14, in authenticate\n    return self.auth_service.validate_credentials(username, password)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\services\\auth_service.py\", line 11, in validate_credentials\n    if not self.db.connection:\n           ^^^^^^^^^^^^^^^^^^\nAttributeError: 'Database' object has no attribute 'connection'. Did you mean: 'get_connection'?"}
{"timestamp": "2025-07-29T11:33:19.731112", "level": "WARNING", "message": "Intento fallido para usuario: luis", "module": "login_window", "function": "authenticate", "line": 75, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:33:53.031504", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 13, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:33:53.033982", "level": "ERROR", "message": "Error en autenticación: 'Database' object has no attribute 'connection'", "module": "auth_controller", "function": "authenticate", "line": 16, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\controllers\\auth_controller.py\", line 14, in authenticate\n    return self.auth_service.validate_credentials(username, password)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\services\\auth_service.py\", line 11, in validate_credentials\n    if not self.db.connection:\n           ^^^^^^^^^^^^^^^^^^\nAttributeError: 'Database' object has no attribute 'connection'. Did you mean: 'get_connection'?"}
{"timestamp": "2025-07-29T11:33:53.038180", "level": "WARNING", "message": "Intento fallido para usuario: luis", "module": "login_window", "function": "authenticate", "line": 75, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:34:01.774341", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 13, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:34:01.777365", "level": "ERROR", "message": "Error en autenticación: 'Database' object has no attribute 'connection'", "module": "auth_controller", "function": "authenticate", "line": 16, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\controllers\\auth_controller.py\", line 14, in authenticate\n    return self.auth_service.validate_credentials(username, password)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\services\\auth_service.py\", line 11, in validate_credentials\n    if not self.db.connection:\n           ^^^^^^^^^^^^^^^^^^\nAttributeError: 'Database' object has no attribute 'connection'. Did you mean: 'get_connection'?"}
{"timestamp": "2025-07-29T11:34:01.781634", "level": "WARNING", "message": "Intento fallido para usuario: luis", "module": "login_window", "function": "authenticate", "line": 75, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:34:05.377756", "level": "INFO", "message": "Intento de login para usuario: luissdfdsfds", "module": "auth_controller", "function": "authenticate", "line": 13, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:34:05.380588", "level": "ERROR", "message": "Error en autenticación: 'Database' object has no attribute 'connection'", "module": "auth_controller", "function": "authenticate", "line": 16, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\controllers\\auth_controller.py\", line 14, in authenticate\n    return self.auth_service.validate_credentials(username, password)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\services\\auth_service.py\", line 11, in validate_credentials\n    if not self.db.connection:\n           ^^^^^^^^^^^^^^^^^^\nAttributeError: 'Database' object has no attribute 'connection'. Did you mean: 'get_connection'?"}
{"timestamp": "2025-07-29T11:34:05.384578", "level": "WARNING", "message": "Intento fallido para usuario: luissdfdsfds", "module": "login_window", "function": "authenticate", "line": 75, "thread": "MainThread"}
{"timestamp": "2025-07-29T11:42:00.559559", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 93, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:07:33.329574", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 44, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:07:33.350044", "level": "WARNING", "message": "No se pudo configurar HiDPI: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "create_application", "line": 32, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:07:33.562238", "level": "INFO", "message": "Interfaz de login mostrada", "module": "main", "function": "main", "line": 64, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:07:39.897279", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 13, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:07:39.898892", "level": "ERROR", "message": "Error en autenticación: 'Database' object has no attribute 'connection'", "module": "auth_controller", "function": "authenticate", "line": 16, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\controllers\\auth_controller.py\", line 14, in authenticate\n    return self.auth_service.validate_credentials(username, password)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\services\\auth_service.py\", line 11, in validate_credentials\n    if not self.db.connection:\n           ^^^^^^^^^^^^^^^^^^\nAttributeError: 'Database' object has no attribute 'connection'. Did you mean: 'get_connection'?"}
{"timestamp": "2025-07-29T13:07:39.907043", "level": "WARNING", "message": "Intento fallido para usuario: luis", "module": "login_window", "function": "authenticate", "line": 75, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:07:52.546484", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 13, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:07:52.546484", "level": "ERROR", "message": "Error en autenticación: 'Database' object has no attribute 'connection'", "module": "auth_controller", "function": "authenticate", "line": 16, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\controllers\\auth_controller.py\", line 14, in authenticate\n    return self.auth_service.validate_credentials(username, password)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\services\\auth_service.py\", line 11, in validate_credentials\n    if not self.db.connection:\n           ^^^^^^^^^^^^^^^^^^\nAttributeError: 'Database' object has no attribute 'connection'. Did you mean: 'get_connection'?"}
{"timestamp": "2025-07-29T13:07:52.552093", "level": "WARNING", "message": "Intento fallido para usuario: luis", "module": "login_window", "function": "authenticate", "line": 75, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:08:03.571497", "level": "INFO", "message": "Intento de login para usuario: carlos", "module": "auth_controller", "function": "authenticate", "line": 13, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:08:03.574189", "level": "ERROR", "message": "Error en autenticación: 'Database' object has no attribute 'connection'", "module": "auth_controller", "function": "authenticate", "line": 16, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\controllers\\auth_controller.py\", line 14, in authenticate\n    return self.auth_service.validate_credentials(username, password)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\services\\auth_service.py\", line 11, in validate_credentials\n    if not self.db.connection:\n           ^^^^^^^^^^^^^^^^^^\nAttributeError: 'Database' object has no attribute 'connection'. Did you mean: 'get_connection'?"}
{"timestamp": "2025-07-29T13:08:03.578192", "level": "WARNING", "message": "Intento fallido para usuario: carlos", "module": "login_window", "function": "authenticate", "line": 75, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:08:43.333092", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 93, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:08:48.811793", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 44, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:08:48.833755", "level": "WARNING", "message": "No se pudo configurar HiDPI: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "create_application", "line": 32, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:08:49.014765", "level": "INFO", "message": "Interfaz de login mostrada", "module": "main", "function": "main", "line": 64, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:08:55.743386", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 13, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:08:55.743386", "level": "ERROR", "message": "Error en autenticación: 'Database' object has no attribute 'connection'", "module": "auth_controller", "function": "authenticate", "line": 16, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\controllers\\auth_controller.py\", line 14, in authenticate\n    return self.auth_service.validate_credentials(username, password)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\services\\auth_service.py\", line 11, in validate_credentials\n    if not self.db.connection:\n           ^^^^^^^^^^^^^^^^^^\nAttributeError: 'Database' object has no attribute 'connection'. Did you mean: 'get_connection'?"}
{"timestamp": "2025-07-29T13:08:55.753775", "level": "WARNING", "message": "Intento fallido para usuario: luis", "module": "login_window", "function": "authenticate", "line": 75, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:09:09.101184", "level": "INFO", "message": "Intento de login para usuario: carlos", "module": "auth_controller", "function": "authenticate", "line": 13, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:09:09.101184", "level": "ERROR", "message": "Error en autenticación: 'Database' object has no attribute 'connection'", "module": "auth_controller", "function": "authenticate", "line": 16, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\controllers\\auth_controller.py\", line 14, in authenticate\n    return self.auth_service.validate_credentials(username, password)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\services\\auth_service.py\", line 11, in validate_credentials\n    if not self.db.connection:\n           ^^^^^^^^^^^^^^^^^^\nAttributeError: 'Database' object has no attribute 'connection'. Did you mean: 'get_connection'?"}
{"timestamp": "2025-07-29T13:09:09.105516", "level": "WARNING", "message": "Intento fallido para usuario: carlos", "module": "login_window", "function": "authenticate", "line": 75, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:09:16.631672", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 13, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:09:16.631672", "level": "ERROR", "message": "Error en autenticación: 'Database' object has no attribute 'connection'", "module": "auth_controller", "function": "authenticate", "line": 16, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\controllers\\auth_controller.py\", line 14, in authenticate\n    return self.auth_service.validate_credentials(username, password)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\services\\auth_service.py\", line 11, in validate_credentials\n    if not self.db.connection:\n           ^^^^^^^^^^^^^^^^^^\nAttributeError: 'Database' object has no attribute 'connection'. Did you mean: 'get_connection'?"}
{"timestamp": "2025-07-29T13:09:16.636554", "level": "WARNING", "message": "Intento fallido para usuario: luis", "module": "login_window", "function": "authenticate", "line": 75, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:10:23.991379", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 93, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:11:23.699238", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 44, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:11:23.723248", "level": "WARNING", "message": "No se pudo configurar HiDPI: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "create_application", "line": 32, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:11:23.908941", "level": "INFO", "message": "Interfaz de login mostrada", "module": "main", "function": "main", "line": 64, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:11:34.279833", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 13, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:11:34.289626", "level": "ERROR", "message": "Error en autenticación: 'Database' object has no attribute 'connection'", "module": "auth_controller", "function": "authenticate", "line": 16, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\controllers\\auth_controller.py\", line 14, in authenticate\n    return self.auth_service.validate_credentials(username, password)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\services\\auth_service.py\", line 11, in validate_credentials\n    if not self.db.connection:\n           ^^^^^^^^^^^^^^^^^^\nAttributeError: 'Database' object has no attribute 'connection'. Did you mean: 'get_connection'?"}
{"timestamp": "2025-07-29T13:11:34.293627", "level": "WARNING", "message": "Intento fallido para usuario: luis", "module": "login_window", "function": "authenticate", "line": 75, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:15:46.096289", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 93, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:15:49.757714", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 44, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:15:49.782611", "level": "WARNING", "message": "No se pudo configurar HiDPI: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "create_application", "line": 32, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:15:49.961490", "level": "INFO", "message": "Interfaz de login mostrada", "module": "main", "function": "main", "line": 64, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:15:55.655648", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 13, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:15:55.709779", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 72, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:15:55.709779", "level": "INFO", "message": "Usuario autenticado: luis", "module": "main", "function": "on_login_success", "line": 54, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:15:55.709779", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 93, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:15:55.740024", "level": "INFO", "message": "Ventana principal creada para luis", "module": "main_window", "function": "__init__", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:16:34.434199", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 44, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:16:34.459264", "level": "WARNING", "message": "No se pudo configurar HiDPI: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "create_application", "line": 32, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:16:34.644883", "level": "INFO", "message": "Interfaz de login mostrada", "module": "main", "function": "main", "line": 64, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:16:39.975166", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 13, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:16:40.029840", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 72, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:16:40.030302", "level": "INFO", "message": "Usuario autenticado: luis", "module": "main", "function": "on_login_success", "line": 54, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:16:40.032029", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 93, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:16:40.054692", "level": "INFO", "message": "Ventana principal creada para luis", "module": "main_window", "function": "__init__", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:19:19.476023", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 44, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:19:19.501119", "level": "WARNING", "message": "No se pudo configurar HiDPI: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "create_application", "line": 32, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:19:19.685638", "level": "INFO", "message": "Interfaz de login mostrada", "module": "main", "function": "main", "line": 64, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:19:24.460964", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 13, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:19:24.514541", "level": "WARNING", "message": "Intento fallido para usuario: luis", "module": "login_window", "function": "authenticate", "line": 75, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:19:30.834545", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 13, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:19:30.889779", "level": "WARNING", "message": "Intento fallido para usuario: luis", "module": "login_window", "function": "authenticate", "line": 75, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:19:37.248766", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 13, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:19:37.305853", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 72, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:19:37.305853", "level": "INFO", "message": "Usuario autenticado: luis", "module": "main", "function": "on_login_success", "line": 54, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:19:37.306856", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 93, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:19:37.332769", "level": "INFO", "message": "Ventana principal creada para luis", "module": "main_window", "function": "__init__", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:30:52.379038", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 43, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:30:52.403429", "level": "WARNING", "message": "No se pudo configurar HiDPI: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "create_application", "line": 31, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:30:52.590716", "level": "INFO", "message": "Interfaz de login mostrada", "module": "main", "function": "main", "line": 69, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:30:57.962626", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 13, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:30:58.013515", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 72, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:30:58.017517", "level": "INFO", "message": "Usuario autenticado: luis", "module": "main", "function": "on_login_success", "line": 56, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:30:58.017517", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 93, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:30:58.036924", "level": "INFO", "message": "Ventana principal creada para luis", "module": "main_window", "function": "__init__", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:31:28.782974", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 43, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:31:28.804642", "level": "WARNING", "message": "No se pudo configurar HiDPI: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "create_application", "line": 31, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:31:28.988186", "level": "INFO", "message": "Interfaz de login mostrada", "module": "main", "function": "main", "line": 69, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:31:32.236219", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 13, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:31:32.289151", "level": "WARNING", "message": "Intento fallido para usuario: luis", "module": "login_window", "function": "authenticate", "line": 75, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:31:38.926438", "level": "INFO", "message": "Intento de login para usuario: carlos", "module": "auth_controller", "function": "authenticate", "line": 13, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:31:38.975775", "level": "WARNING", "message": "Intento fallido para usuario: carlos", "module": "login_window", "function": "authenticate", "line": 75, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:31:43.838055", "level": "INFO", "message": "Intento de login para usuario: carlos", "module": "auth_controller", "function": "authenticate", "line": 13, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:31:43.893369", "level": "INFO", "message": "Usuario autenticado: carlos", "module": "login_window", "function": "authenticate", "line": 72, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:31:43.893369", "level": "INFO", "message": "Usuario autenticado: carlos", "module": "main", "function": "on_login_success", "line": 56, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:31:43.893369", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 93, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:31:43.916625", "level": "INFO", "message": "Ventana principal creada para carlos", "module": "main_window", "function": "__init__", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:58:18.470192", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 43, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:58:18.490880", "level": "WARNING", "message": "No se pudo configurar HiDPI: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "create_application", "line": 31, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:58:18.628434", "level": "CRITICAL", "message": "Error al iniciar aplicación: cannot import name 'QAction' from 'PyQt6.QtWidgets' (E:\\MODELO MACHINE LEARNING TOTAL\\EXE\\envs\\nova-desktop\\Lib\\site-packages\\PyQt6\\QtWidgets.pyd)", "module": "main", "function": "main", "line": 76, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 53, in main\n    from app.views.main_window import MainWindow\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\main_window.py\", line 2, in <module>\n    from PyQt6.QtWidgets import (QMainWindow, QVBoxLayout, QWidget, QLabel,\nImportError: cannot import name 'QAction' from 'PyQt6.QtWidgets' (E:\\MODELO MACHINE LEARNING TOTAL\\EXE\\envs\\nova-desktop\\Lib\\site-packages\\PyQt6\\QtWidgets.pyd)"}
{"timestamp": "2025-07-29T13:58:28.621181", "level": "INFO", "message": "Todas las conexiones de la pool cerradas", "module": "database", "function": "close_all_connections", "line": 54, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:58:34.395617", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 43, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:58:34.417170", "level": "WARNING", "message": "No se pudo configurar HiDPI: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "create_application", "line": 31, "thread": "MainThread"}
{"timestamp": "2025-07-29T13:58:34.551044", "level": "CRITICAL", "message": "Error al iniciar aplicación: cannot import name 'QAction' from 'PyQt6.QtWidgets' (E:\\MODELO MACHINE LEARNING TOTAL\\EXE\\envs\\nova-desktop\\Lib\\site-packages\\PyQt6\\QtWidgets.pyd)", "module": "main", "function": "main", "line": 76, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 53, in main\n    from app.views.main_window import MainWindow\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\main_window.py\", line 2, in <module>\n    from PyQt6.QtWidgets import (QMainWindow, QVBoxLayout, QWidget, QLabel,\nImportError: cannot import name 'QAction' from 'PyQt6.QtWidgets' (E:\\MODELO MACHINE LEARNING TOTAL\\EXE\\envs\\nova-desktop\\Lib\\site-packages\\PyQt6\\QtWidgets.pyd)"}
{"timestamp": "2025-07-29T13:58:36.167157", "level": "INFO", "message": "Todas las conexiones de la pool cerradas", "module": "database", "function": "close_all_connections", "line": 54, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:00:48.317778", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 43, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:00:48.343456", "level": "WARNING", "message": "No se pudo configurar HiDPI: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "create_application", "line": 31, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:00:48.558549", "level": "INFO", "message": "Interfaz de login mostrada", "module": "main", "function": "main", "line": 71, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:00:53.805260", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 13, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:00:53.851043", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 72, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:00:53.862423", "level": "CRITICAL", "message": "Excepción no capturada", "module": "main", "function": "handle_exception", "line": 21, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 56, in on_login_success\n    if auth_result['authenticated']:\n       ~~~~~~~~~~~^^^^^^^^^^^^^^^^^\nTypeError: string indices must be integers, not 'str'"}
{"timestamp": "2025-07-29T14:01:16.260611", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 13, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:01:16.314158", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 72, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:01:16.314158", "level": "CRITICAL", "message": "Excepción no capturada", "module": "main", "function": "handle_exception", "line": 21, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 56, in on_login_success\n    if auth_result['authenticated']:\n       ~~~~~~~~~~~^^^^^^^^^^^^^^^^^\nTypeError: string indices must be integers, not 'str'"}
{"timestamp": "2025-07-29T14:01:23.020090", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 13, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:01:23.072276", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 72, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:01:23.076283", "level": "CRITICAL", "message": "Excepción no capturada", "module": "main", "function": "handle_exception", "line": 21, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 56, in on_login_success\n    if auth_result['authenticated']:\n       ~~~~~~~~~~~^^^^^^^^^^^^^^^^^\nTypeError: string indices must be integers, not 'str'"}
{"timestamp": "2025-07-29T14:01:27.231441", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 93, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:18:41.066126", "level": "CRITICAL", "message": "Error al iniciar aplicación: 'LoginWindow' object has no attribute 'init_ui'", "module": "main", "function": "main", "line": 48, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 24, in main\n    login_window = LoginWindow(auth_controller)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\login_window.py\", line 18, in __init__\n    self.init_ui()\n    ^^^^^^^^^^^^\nAttributeError: 'LoginWindow' object has no attribute 'init_ui'"}
{"timestamp": "2025-07-29T14:18:45.045227", "level": "INFO", "message": "Todas las conexiones de la pool cerradas", "module": "database", "function": "close_all_connections", "line": 54, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:18:47.412288", "level": "CRITICAL", "message": "Error al iniciar aplicación: 'LoginWindow' object has no attribute 'init_ui'", "module": "main", "function": "main", "line": 48, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 24, in main\n    login_window = LoginWindow(auth_controller)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\login_window.py\", line 18, in __init__\n    self.init_ui()\n    ^^^^^^^^^^^^\nAttributeError: 'LoginWindow' object has no attribute 'init_ui'"}
{"timestamp": "2025-07-29T14:18:48.875120", "level": "INFO", "message": "Todas las conexiones de la pool cerradas", "module": "database", "function": "close_all_connections", "line": 54, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:20:44.429825", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:20:44.484384", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 74, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:20:44.485006", "level": "INFO", "message": "Usuario autenticado: luis (Perfil: 0)", "module": "main", "function": "on_login_success", "line": 34, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:20:44.487999", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 95, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:24:55.662255", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:24:55.716784", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 74, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:24:55.716784", "level": "INFO", "message": "Usuario autenticado: luis (Perfil: 0)", "module": "main", "function": "on_login_success", "line": 34, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:24:55.720872", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 95, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:24:55.746942", "level": "INFO", "message": "Ventana principal creada para luis (Perfil: 0)", "module": "main_window", "function": "__init__", "line": 17, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:25:00.860153", "level": "INFO", "message": "Ventana principal cerrada para usuario: luis", "module": "main_window", "function": "closeEvent", "line": 69, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:25:37.211824", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:25:37.287779", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 74, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:25:37.288264", "level": "INFO", "message": "Usuario autenticado: luis (Perfil: 0)", "module": "main", "function": "on_login_success", "line": 34, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:25:37.291258", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 95, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:25:37.321081", "level": "INFO", "message": "Ventana principal creada para luis (Perfil: 0)", "module": "main_window", "function": "__init__", "line": 17, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:31:41.461864", "level": "INFO", "message": "Ventana principal cerrada para usuario: luis", "module": "main_window", "function": "closeEvent", "line": 69, "thread": "MainThread"}
{"timestamp": "2025-07-29T14:31:45.894923", "level": "CRITICAL", "message": "Error al iniciar aplicación: cannot import name 'QAction' from 'PyQt6.QtWidgets' (E:\\MODELO MACHINE LEARNING TOTAL\\EXE\\envs\\nova-desktop\\Lib\\site-packages\\PyQt6\\QtWidgets.pyd)", "module": "main", "function": "main", "line": 48, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 26, in main\n    from app.views.main_window import MainWindow\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\main_window.py\", line 2, in <module>\n    from PyQt6.QtWidgets import (QMainWindow, QVBoxLayout, QWidget, QLabel,\nImportError: cannot import name 'QAction' from 'PyQt6.QtWidgets' (E:\\MODELO MACHINE LEARNING TOTAL\\EXE\\envs\\nova-desktop\\Lib\\site-packages\\PyQt6\\QtWidgets.pyd)"}
{"timestamp": "2025-07-29T14:32:09.668475", "level": "INFO", "message": "Todas las conexiones de la pool cerradas", "module": "database", "function": "close_all_connections", "line": 54, "thread": "MainThread"}
{"timestamp": "2025-07-29T15:25:25.346960", "level": "CRITICAL", "message": "Error al iniciar aplicación: cannot import name 'QAction' from 'PyQt6.QtWidgets' (E:\\MODELO MACHINE LEARNING TOTAL\\EXE\\envs\\nova-desktop\\Lib\\site-packages\\PyQt6\\QtWidgets.pyd)", "module": "main", "function": "main", "line": 48, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 26, in main\n    from app.views.main_window import MainWindow\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\main_window.py\", line 2, in <module>\n    from PyQt6.QtWidgets import (QMainWindow, QVBoxLayout, QWidget, QLabel,\nImportError: cannot import name 'QAction' from 'PyQt6.QtWidgets' (E:\\MODELO MACHINE LEARNING TOTAL\\EXE\\envs\\nova-desktop\\Lib\\site-packages\\PyQt6\\QtWidgets.pyd)"}
{"timestamp": "2025-07-29T15:25:26.962167", "level": "INFO", "message": "Todas las conexiones de la pool cerradas", "module": "database", "function": "close_all_connections", "line": 54, "thread": "MainThread"}
{"timestamp": "2025-07-29T15:26:03.830503", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T15:26:03.887879", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 74, "thread": "MainThread"}
{"timestamp": "2025-07-29T15:26:03.888374", "level": "INFO", "message": "Usuario autenticado: luis (Perfil: 0)", "module": "main", "function": "on_login_success", "line": 34, "thread": "MainThread"}
{"timestamp": "2025-07-29T15:26:03.891368", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 95, "thread": "MainThread"}
{"timestamp": "2025-07-29T15:26:03.918811", "level": "CRITICAL", "message": "Excepción no capturada", "module": "logger", "function": "handle_exception", "line": 138, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 37, in on_login_success\n    main_window = MainWindow(username, profile)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: MainWindow.__init__() missing 1 required positional argument: 'db_connection'"}
{"timestamp": "2025-07-29T15:29:37.143621", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T15:29:37.203501", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 74, "thread": "MainThread"}
{"timestamp": "2025-07-29T15:29:37.203501", "level": "INFO", "message": "Usuario autenticado: luis (Perfil: 0)", "module": "main", "function": "on_login_success", "line": 34, "thread": "MainThread"}
{"timestamp": "2025-07-29T15:29:37.207594", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 95, "thread": "MainThread"}
{"timestamp": "2025-07-29T15:29:37.232417", "level": "INFO", "message": "Ventana principal creada para luis (Perfil: 0)", "module": "main_window", "function": "__init__", "line": 17, "thread": "MainThread"}
{"timestamp": "2025-07-29T15:34:45.019232", "level": "INFO", "message": "Ventana principal cerrada para usuario: luis", "module": "main_window", "function": "closeEvent", "line": 69, "thread": "MainThread"}
{"timestamp": "2025-07-29T15:49:13.435647", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T15:49:13.490459", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 74, "thread": "MainThread"}
{"timestamp": "2025-07-29T15:49:13.490868", "level": "INFO", "message": "Usuario autenticado: luis (Perfil: 0)", "module": "main", "function": "on_login_success", "line": 34, "thread": "MainThread"}
{"timestamp": "2025-07-29T15:49:13.494333", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 95, "thread": "MainThread"}
{"timestamp": "2025-07-29T15:49:13.525322", "level": "INFO", "message": "Ventana principal creada para luis (Perfil: 0)", "module": "main_window", "function": "__init__", "line": 17, "thread": "MainThread"}
{"timestamp": "2025-07-29T15:56:44.496018", "level": "INFO", "message": "Ventana principal cerrada para usuario: luis", "module": "main_window", "function": "closeEvent", "line": 69, "thread": "MainThread"}
{"timestamp": "2025-07-29T15:56:53.602630", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T15:56:53.663052", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 74, "thread": "MainThread"}
{"timestamp": "2025-07-29T15:56:53.663708", "level": "INFO", "message": "Usuario autenticado: luis (Perfil: 0)", "module": "main", "function": "on_login_success", "line": 34, "thread": "MainThread"}
{"timestamp": "2025-07-29T15:56:53.666751", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 95, "thread": "MainThread"}
{"timestamp": "2025-07-29T15:56:53.695586", "level": "INFO", "message": "Ventana principal creada para luis (Perfil: 0)", "module": "main_window", "function": "__init__", "line": 18, "thread": "MainThread"}
{"timestamp": "2025-07-29T15:57:30.151687", "level": "INFO", "message": "Usuario agregado: luis1", "module": "main_window", "function": "mostrar_formulario_agregar", "line": 103, "thread": "MainThread"}
{"timestamp": "2025-07-29T15:57:57.055884", "level": "INFO", "message": "Listado de usuarios mostrado", "module": "main_window", "function": "mostrar_lista_usuarios", "line": 96, "thread": "MainThread"}
{"timestamp": "2025-07-29T16:25:45.979169", "level": "INFO", "message": "Listado de usuarios mostrado", "module": "main_window", "function": "mostrar_lista_usuarios", "line": 96, "thread": "MainThread"}
{"timestamp": "2025-07-29T16:25:48.208570", "level": "INFO", "message": "Ventana principal cerrada para usuario: luis", "module": "main_window", "function": "closeEvent", "line": 124, "thread": "MainThread"}
{"timestamp": "2025-07-29T16:25:54.991573", "level": "CRITICAL", "message": "Error al iniciar aplicación: unmatched ')' (main_window.py, line 61)", "module": "main", "function": "main", "line": 48, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 26, in main\n    from app.views.main_window import MainWindow\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\main_window.py\", line 61\n    self.table.setItem(row, 1, QTableWidgetItem(user['username'])))\n                                                                  ^\nSyntaxError: unmatched ')'"}
{"timestamp": "2025-07-29T16:26:01.727126", "level": "INFO", "message": "Todas las conexiones de la pool cerradas", "module": "database", "function": "close_all_connections", "line": 54, "thread": "MainThread"}
{"timestamp": "2025-07-29T16:32:59.111488", "level": "CRITICAL", "message": "Error al iniciar aplicación: unmatched ')' (main_window.py, line 62)", "module": "main", "function": "main", "line": 48, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 26, in main\n    from app.views.main_window import MainWindow\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\main_window.py\", line 62\n    self.table.setItem(row, 1, QTableWidgetItem(user['username'])))\n                                                                  ^\nSyntaxError: unmatched ')'"}
{"timestamp": "2025-07-29T16:33:01.773639", "level": "INFO", "message": "Todas las conexiones de la pool cerradas", "module": "database", "function": "close_all_connections", "line": 54, "thread": "MainThread"}
{"timestamp": "2025-07-29T16:35:30.033131", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T16:35:30.125694", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 74, "thread": "MainThread"}
{"timestamp": "2025-07-29T16:35:30.126665", "level": "INFO", "message": "Usuario autenticado: luis (Perfil: 0)", "module": "main", "function": "on_login_success", "line": 34, "thread": "MainThread"}
{"timestamp": "2025-07-29T16:35:30.131651", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 95, "thread": "MainThread"}
{"timestamp": "2025-07-29T16:35:30.150618", "level": "INFO", "message": "Ventana principal creada para luis (Perfil: 0)", "module": "main_window", "function": "__init__", "line": 197, "thread": "MainThread"}
{"timestamp": "2025-07-29T16:37:44.582276", "level": "INFO", "message": "Ventana principal cerrada para usuario: luis", "module": "main_window", "function": "closeEvent", "line": 256, "thread": "MainThread"}
{"timestamp": "2025-07-29T16:37:57.270411", "level": "INFO", "message": "Intento de login para usuario: carlos", "module": "auth_controller", "function": "authenticate", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T16:37:57.325052", "level": "INFO", "message": "Usuario autenticado: carlos", "module": "login_window", "function": "authenticate", "line": 74, "thread": "MainThread"}
{"timestamp": "2025-07-29T16:37:57.325747", "level": "INFO", "message": "Usuario autenticado: carlos (Perfil: 1)", "module": "main", "function": "on_login_success", "line": 34, "thread": "MainThread"}
{"timestamp": "2025-07-29T16:37:57.329079", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 95, "thread": "MainThread"}
{"timestamp": "2025-07-29T16:37:57.356850", "level": "INFO", "message": "Ventana principal creada para carlos (Perfil: 1)", "module": "main_window", "function": "__init__", "line": 197, "thread": "MainThread"}
{"timestamp": "2025-07-29T16:43:33.554434", "level": "INFO", "message": "Ventana principal cerrada para usuario: carlos", "module": "main_window", "function": "closeEvent", "line": 256, "thread": "MainThread"}
{"timestamp": "2025-07-29T16:43:47.014265", "level": "INFO", "message": "Intento de login para usuario: carlos", "module": "auth_controller", "function": "authenticate", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T16:43:47.068419", "level": "INFO", "message": "Usuario autenticado: carlos", "module": "login_window", "function": "authenticate", "line": 74, "thread": "MainThread"}
{"timestamp": "2025-07-29T16:43:47.069689", "level": "INFO", "message": "Usuario autenticado: carlos (Perfil: 1)", "module": "main", "function": "on_login_success", "line": 34, "thread": "MainThread"}
{"timestamp": "2025-07-29T16:43:47.072622", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 95, "thread": "MainThread"}
{"timestamp": "2025-07-29T16:43:47.095005", "level": "INFO", "message": "Ventana principal creada para carlos (Perfil: 1)", "module": "main_window", "function": "__init__", "line": 197, "thread": "MainThread"}
{"timestamp": "2025-07-29T16:47:41.999577", "level": "INFO", "message": "Ventana principal cerrada para usuario: carlos", "module": "main_window", "function": "closeEvent", "line": 256, "thread": "MainThread"}
{"timestamp": "2025-07-29T17:05:11.228607", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T17:05:11.284679", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 74, "thread": "MainThread"}
{"timestamp": "2025-07-29T17:05:11.285553", "level": "INFO", "message": "Usuario autenticado: luis (Perfil: 0)", "module": "main", "function": "on_login_success", "line": 34, "thread": "MainThread"}
{"timestamp": "2025-07-29T17:05:11.289578", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 95, "thread": "MainThread"}
{"timestamp": "2025-07-29T17:05:11.314149", "level": "INFO", "message": "Ventana principal creada para luis (Perfil: 0)", "module": "main_window", "function": "__init__", "line": 298, "thread": "MainThread"}
{"timestamp": "2025-07-29T17:05:16.809616", "level": "INFO", "message": "Todas las conexiones de la pool cerradas", "module": "database", "function": "close_all_connections", "line": 54, "thread": "MainThread"}
{"timestamp": "2025-07-29T17:20:58.165461", "level": "INFO", "message": "Ventana principal cerrada para usuario: luis", "module": "main_window", "function": "closeEvent", "line": 374, "thread": "MainThread"}
{"timestamp": "2025-07-29T17:21:15.685301", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T17:21:15.740601", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 74, "thread": "MainThread"}
{"timestamp": "2025-07-29T17:21:15.741599", "level": "INFO", "message": "Usuario autenticado: luis (Perfil: 0)", "module": "main", "function": "on_login_success", "line": 34, "thread": "MainThread"}
{"timestamp": "2025-07-29T17:21:15.745640", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 95, "thread": "MainThread"}
{"timestamp": "2025-07-29T17:21:16.080524", "level": "INFO", "message": "Ventana principal creada para luis (Perfil: 0)", "module": "main_window", "function": "__init__", "line": 28, "thread": "MainThread"}
{"timestamp": "2025-07-29T17:21:19.252424", "level": "CRITICAL", "message": "Excepción no capturada", "module": "logger", "function": "handle_exception", "line": 138, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\main_window.py\", line 92, in show_user_management\n    dialog = UserManagementDialog(self)\n             ^^^^^^^^^^^^^^^^^^^^\nNameError: name 'UserManagementDialog' is not defined"}
{"timestamp": "2025-07-29T17:21:39.252656", "level": "INFO", "message": "Ventana principal cerrada para usuario: luis", "module": "main_window", "function": "closeEvent", "line": 98, "thread": "MainThread"}
{"timestamp": "2025-07-29T17:22:23.918038", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T17:22:23.973734", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 74, "thread": "MainThread"}
{"timestamp": "2025-07-29T17:22:23.974216", "level": "INFO", "message": "Usuario autenticado: luis (Perfil: 0)", "module": "main", "function": "on_login_success", "line": 34, "thread": "MainThread"}
{"timestamp": "2025-07-29T17:22:23.977210", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 95, "thread": "MainThread"}
{"timestamp": "2025-07-29T17:22:24.002576", "level": "INFO", "message": "Ventana principal creada para luis (Perfil: 0)", "module": "main_window", "function": "__init__", "line": 197, "thread": "MainThread"}
{"timestamp": "2025-07-29T17:22:29.156389", "level": "INFO", "message": "Todas las conexiones de la pool cerradas", "module": "database", "function": "close_all_connections", "line": 54, "thread": "MainThread"}
{"timestamp": "2025-07-29T17:22:39.139837", "level": "INFO", "message": "Ventana principal cerrada para usuario: luis", "module": "main_window", "function": "closeEvent", "line": 256, "thread": "MainThread"}
{"timestamp": "2025-07-29T17:46:17.275304", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T17:46:17.333460", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 74, "thread": "MainThread"}
{"timestamp": "2025-07-29T17:46:17.333460", "level": "INFO", "message": "Usuario autenticado: luis (Perfil: 0)", "module": "main", "function": "on_login_success", "line": 34, "thread": "MainThread"}
{"timestamp": "2025-07-29T17:46:17.337495", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 95, "thread": "MainThread"}
{"timestamp": "2025-07-29T17:46:18.689336", "level": "INFO", "message": "Ventana principal creada para luis (Perfil: 0)", "module": "main_window", "function": "__init__", "line": 200, "thread": "MainThread"}
{"timestamp": "2025-07-29T17:46:23.200606", "level": "INFO", "message": "Todas las conexiones de la pool cerradas", "module": "database", "function": "close_all_connections", "line": 54, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:24:52.791952", "level": "INFO", "message": "Ventana principal cerrada para usuario: luis", "module": "main_window", "function": "closeEvent", "line": 272, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:25:10.606670", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:25:10.687314", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 74, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:25:10.688301", "level": "INFO", "message": "Usuario autenticado: luis (Perfil: 0)", "module": "main", "function": "on_login_success", "line": 34, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:25:10.691859", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 95, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:25:11.339739", "level": "INFO", "message": "Ventana principal creada para luis (Perfil: 0)", "module": "main_window", "function": "__init__", "line": 200, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:25:15.835075", "level": "INFO", "message": "Todas las conexiones de la pool cerradas", "module": "database", "function": "close_all_connections", "line": 54, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:25:34.889629", "level": "CRITICAL", "message": "Excepción no capturada", "module": "logger", "function": "handle_exception", "line": 138, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\video_panel.py\", line 164, in update_mode_display\n    self.video_controller.set_detection_mode('face')\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'VideoController' object has no attribute 'set_detection_mode'"}
{"timestamp": "2025-07-29T18:25:34.896705", "level": "CRITICAL", "message": "Excepción no capturada", "module": "logger", "function": "handle_exception", "line": 138, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\video_panel.py\", line 164, in update_mode_display\n    self.video_controller.set_detection_mode('face')\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'VideoController' object has no attribute 'set_detection_mode'"}
{"timestamp": "2025-07-29T18:25:36.912251", "level": "CRITICAL", "message": "Excepción no capturada", "module": "logger", "function": "handle_exception", "line": 138, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\video_panel.py\", line 160, in update_mode_display\n    self.video_controller.set_detection_mode('object')\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'VideoController' object has no attribute 'set_detection_mode'"}
{"timestamp": "2025-07-29T18:25:36.918474", "level": "CRITICAL", "message": "Excepción no capturada", "module": "logger", "function": "handle_exception", "line": 138, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\video_panel.py\", line 160, in update_mode_display\n    self.video_controller.set_detection_mode('object')\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'VideoController' object has no attribute 'set_detection_mode'"}
{"timestamp": "2025-07-29T18:25:42.356533", "level": "CRITICAL", "message": "Excepción no capturada", "module": "logger", "function": "handle_exception", "line": 138, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\video_panel.py\", line 164, in update_mode_display\n    self.video_controller.set_detection_mode('face')\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'VideoController' object has no attribute 'set_detection_mode'"}
{"timestamp": "2025-07-29T18:25:42.363146", "level": "CRITICAL", "message": "Excepción no capturada", "module": "logger", "function": "handle_exception", "line": 138, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\video_panel.py\", line 164, in update_mode_display\n    self.video_controller.set_detection_mode('face')\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'VideoController' object has no attribute 'set_detection_mode'"}
{"timestamp": "2025-07-29T18:25:47.582048", "level": "CRITICAL", "message": "Excepción no capturada", "module": "logger", "function": "handle_exception", "line": 138, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\video_panel.py\", line 181, in toggle_video\n    if self.video_controller.start_video(self.update_video_frame):\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: VideoController.start_video() takes 1 positional argument but 2 were given"}
{"timestamp": "2025-07-29T18:26:02.560218", "level": "CRITICAL", "message": "Excepción no capturada", "module": "logger", "function": "handle_exception", "line": 138, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\video_panel.py\", line 160, in update_mode_display\n    self.video_controller.set_detection_mode('object')\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'VideoController' object has no attribute 'set_detection_mode'"}
{"timestamp": "2025-07-29T18:26:02.567159", "level": "CRITICAL", "message": "Excepción no capturada", "module": "logger", "function": "handle_exception", "line": 138, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\video_panel.py\", line 160, in update_mode_display\n    self.video_controller.set_detection_mode('object')\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'VideoController' object has no attribute 'set_detection_mode'"}
{"timestamp": "2025-07-29T18:26:05.719295", "level": "CRITICAL", "message": "Excepción no capturada", "module": "logger", "function": "handle_exception", "line": 138, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\video_panel.py\", line 181, in toggle_video\n    if self.video_controller.start_video(self.update_video_frame):\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: VideoController.start_video() takes 1 positional argument but 2 were given"}
{"timestamp": "2025-07-29T18:27:46.126484", "level": "CRITICAL", "message": "Excepción no capturada", "module": "logger", "function": "handle_exception", "line": 138, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\video_panel.py\", line 169, in change_object\n    self.video_controller.set_target_object(self.selected_object)\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'VideoController' object has no attribute 'set_target_object'"}
{"timestamp": "2025-07-29T18:27:47.249766", "level": "CRITICAL", "message": "Excepción no capturada", "module": "logger", "function": "handle_exception", "line": 138, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\video_panel.py\", line 181, in toggle_video\n    if self.video_controller.start_video(self.update_video_frame):\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: VideoController.start_video() takes 1 positional argument but 2 were given"}
{"timestamp": "2025-07-29T18:28:29.381168", "level": "INFO", "message": "Ventana principal cerrada para usuario: luis", "module": "main_window", "function": "closeEvent", "line": 272, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:28:47.724328", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:28:47.783646", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 74, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:28:47.783646", "level": "INFO", "message": "Usuario autenticado: luis (Perfil: 0)", "module": "main", "function": "on_login_success", "line": 34, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:28:47.788635", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 95, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:28:48.432270", "level": "INFO", "message": "Ventana principal creada para luis (Perfil: 0)", "module": "main_window", "function": "__init__", "line": 200, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:28:55.428290", "level": "CRITICAL", "message": "Excepción no capturada", "module": "logger", "function": "handle_exception", "line": 138, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\video_panel.py\", line 164, in update_mode_display\n    self.video_controller.set_detection_mode('face')\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'VideoController' object has no attribute 'set_detection_mode'"}
{"timestamp": "2025-07-29T18:28:55.435043", "level": "CRITICAL", "message": "Excepción no capturada", "module": "logger", "function": "handle_exception", "line": 138, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\video_panel.py\", line 164, in update_mode_display\n    self.video_controller.set_detection_mode('face')\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'VideoController' object has no attribute 'set_detection_mode'"}
{"timestamp": "2025-07-29T18:37:32.600361", "level": "INFO", "message": "Ventana principal cerrada para usuario: luis", "module": "main_window", "function": "closeEvent", "line": 272, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:37:51.243343", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:37:51.297356", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 74, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:37:51.297856", "level": "INFO", "message": "Usuario autenticado: luis (Perfil: 0)", "module": "main", "function": "on_login_success", "line": 34, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:37:51.301894", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 95, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:37:51.932916", "level": "INFO", "message": "Ventana principal creada para luis (Perfil: 0)", "module": "main_window", "function": "__init__", "line": 200, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:37:55.185651", "level": "INFO", "message": "Todas las conexiones de la pool cerradas", "module": "database", "function": "close_all_connections", "line": 54, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:37:56.807407", "level": "CRITICAL", "message": "Excepción no capturada", "module": "logger", "function": "handle_exception", "line": 138, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\main_window.py\", line 261, in show_video_panel\n    self.video_panel = VideoPanel(self.video_controller, self.username)\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\video_panel.py\", line 24, in __init__\n    self.init_ui()\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\video_panel.py\", line 56, in init_ui\n    self.obj_combo.currentIndexChanged.connect(self.change_object)\n                                               ^^^^^^^^^^^^^^^^^^\nAttributeError: 'VideoPanel' object has no attribute 'change_object'"}
{"timestamp": "2025-07-29T18:41:59.644945", "level": "INFO", "message": "Ventana principal cerrada para usuario: luis", "module": "main_window", "function": "closeEvent", "line": 272, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:42:16.368474", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:42:16.423654", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 74, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:42:16.424573", "level": "INFO", "message": "Usuario autenticado: luis (Perfil: 0)", "module": "main", "function": "on_login_success", "line": 34, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:42:16.426614", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 95, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:42:17.077982", "level": "INFO", "message": "Ventana principal creada para luis (Perfil: 0)", "module": "main_window", "function": "__init__", "line": 200, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:42:20.250897", "level": "CRITICAL", "message": "Excepción no capturada", "module": "logger", "function": "handle_exception", "line": 138, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\main_window.py\", line 261, in show_video_panel\n    self.video_panel = VideoPanel(self.video_controller, self.username)\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\video_panel.py\", line 24, in __init__\n    self.init_ui()\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\video_panel.py\", line 154, in init_ui\n    self.change_mask_method()  # Establecer método inicial\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\video_panel.py\", line 167, in change_mask_method\n    self.video_controller.set_mask_method(method)\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\controllers\\video_controller.py\", line 26, in set_mask_method\n    self.video_service.set_mask_method(method)\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'VideoService' object has no attribute 'set_mask_method'. Did you mean: 'mask_method'?"}
{"timestamp": "2025-07-29T18:50:32.380765", "level": "CRITICAL", "message": "Excepción no capturada", "module": "logger", "function": "handle_exception", "line": 138, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\main_window.py\", line 261, in show_video_panel\n    self.video_panel = VideoPanel(self.video_controller, self.username)\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\video_panel.py\", line 24, in __init__\n    self.init_ui()\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\video_panel.py\", line 154, in init_ui\n    self.change_mask_method()  # Establecer método inicial\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\video_panel.py\", line 167, in change_mask_method\n    self.video_controller.set_mask_method(method)\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\controllers\\video_controller.py\", line 26, in set_mask_method\n    self.video_service.set_mask_method(method)\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'VideoService' object has no attribute 'set_mask_method'. Did you mean: 'mask_method'?"}
{"timestamp": "2025-07-29T18:50:40.550362", "level": "INFO", "message": "Ventana principal cerrada para usuario: luis", "module": "main_window", "function": "closeEvent", "line": 272, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:50:55.082787", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:50:55.154400", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 74, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:50:55.154400", "level": "INFO", "message": "Usuario autenticado: luis (Perfil: 0)", "module": "main", "function": "on_login_success", "line": 34, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:50:55.161299", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 95, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:50:55.818780", "level": "INFO", "message": "Ventana principal creada para luis (Perfil: 0)", "module": "main_window", "function": "__init__", "line": 200, "thread": "MainThread"}
{"timestamp": "2025-07-29T18:51:00.289959", "level": "CRITICAL", "message": "Excepción no capturada", "module": "logger", "function": "handle_exception", "line": 138, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\main_window.py\", line 261, in show_video_panel\n    self.video_panel = VideoPanel(self.video_controller, self.username)\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\video_panel.py\", line 24, in __init__\n    self.init_ui()\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\video_panel.py\", line 154, in init_ui\n    self.change_mask_method()  # Establecer método inicial\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\video_panel.py\", line 167, in change_mask_method\n    self.video_controller.set_mask_method(method)\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\controllers\\video_controller.py\", line 26, in set_mask_method\n    self.video_service.set_mask_method(method)\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'VideoService' object has no attribute 'set_mask_method'. Did you mean: 'mask_method'?"}
{"timestamp": "2025-07-29T19:10:35.966477", "level": "INFO", "message": "Ventana principal cerrada para usuario: luis", "module": "main_window", "function": "closeEvent", "line": 272, "thread": "MainThread"}
{"timestamp": "2025-07-29T19:10:49.212901", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T19:10:49.268748", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 74, "thread": "MainThread"}
{"timestamp": "2025-07-29T19:10:49.269329", "level": "INFO", "message": "Usuario autenticado: luis (Perfil: 0)", "module": "main", "function": "on_login_success", "line": 34, "thread": "MainThread"}
{"timestamp": "2025-07-29T19:10:49.271327", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 95, "thread": "MainThread"}
{"timestamp": "2025-07-29T19:10:49.923161", "level": "INFO", "message": "Ventana principal creada para luis (Perfil: 0)", "module": "main_window", "function": "__init__", "line": 200, "thread": "MainThread"}
{"timestamp": "2025-07-29T19:17:30.063664", "level": "INFO", "message": "Ventana principal cerrada para usuario: luis", "module": "main_window", "function": "closeEvent", "line": 272, "thread": "MainThread"}
{"timestamp": "2025-07-29T19:17:57.274660", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T19:17:57.331229", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 74, "thread": "MainThread"}
{"timestamp": "2025-07-29T19:17:57.331229", "level": "INFO", "message": "Usuario autenticado: luis (Perfil: 0)", "module": "main", "function": "on_login_success", "line": 34, "thread": "MainThread"}
{"timestamp": "2025-07-29T19:17:57.335256", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 95, "thread": "MainThread"}
{"timestamp": "2025-07-29T19:17:57.998598", "level": "INFO", "message": "Ventana principal creada para luis (Perfil: 0)", "module": "main_window", "function": "__init__", "line": 200, "thread": "MainThread"}
{"timestamp": "2025-07-29T19:28:13.407675", "level": "INFO", "message": "Ventana principal cerrada para usuario: luis", "module": "main_window", "function": "closeEvent", "line": 272, "thread": "MainThread"}
{"timestamp": "2025-07-29T19:28:29.464433", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-29T19:28:29.518904", "level": "INFO", "message": "Usuario autenticado: luis", "module": "login_window", "function": "authenticate", "line": 74, "thread": "MainThread"}
{"timestamp": "2025-07-29T19:28:29.519441", "level": "INFO", "message": "Usuario autenticado: luis (Perfil: 0)", "module": "main", "function": "on_login_success", "line": 34, "thread": "MainThread"}
{"timestamp": "2025-07-29T19:28:29.524430", "level": "INFO", "message": "Ventana de login cerrada", "module": "login_window", "function": "closeEvent", "line": 95, "thread": "MainThread"}
{"timestamp": "2025-07-29T19:28:30.206130", "level": "INFO", "message": "Ventana principal creada para luis (Perfil: 0)", "module": "main_window", "function": "__init__", "line": 200, "thread": "MainThread"}
{"timestamp": "2025-07-29T19:28:33.925492", "level": "INFO", "message": "Todas las conexiones de la pool cerradas", "module": "database", "function": "close_all_connections", "line": 54, "thread": "MainThread"}
{"timestamp": "2025-07-29T19:38:31.563054", "level": "INFO", "message": "Ventana principal cerrada para usuario: luis", "module": "main_window", "function": "closeEvent", "line": 272, "thread": "MainThread"}
